#!/usr/bin/env sh
uwebzockets_zig=${UWEBZOCKETS_ZIG:-zig}
if [ -n "${UWEBZOCKETS_TARGET:-}" ]; then
    exec "$uwebzockets_zig" cc -target "$UWEBZOCKETS_TARGET" "$@"
fi
exec "$uwebzockets_zig" cc "$@"
